version: '3.9'

services:
  backend:
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      PGPORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
